### ISSUE TITLE
openscoring can't read output .pmml

### ISSUE THREAD

**Issue by arnaudmkonan** [jpmml/jpmml-h2o#1]
I am testing out this tool and openscoring for some future actual use case. 
i was able to get the openscoring working using the pmml that came with the repos.
but when i create a pmml from h2o using jpmml-h2o, the output pmml can't be read by openscoring i can't figure out why.  Any help pointing the a solution would be appreciated.
Thank you!
Warning: Couldn't read data from file "xgboost_test1.pmml", this makes an empty 
Warning: POST.      

`{   
  "message" : "Bad Request"     
}`

**Comment by vruusmann** [comment]
> Warning: Couldn't read data from file "xgboost_test1.pmml", this makes an empty
> Warning: POST.
> { "message" : "Bad Request" }

Simple - you have misspelled the name of the PMML file - the model deployment request (sent using HTTP POST) did not contain any model information at all.
