### ISSUE TITLE
Output PMML file too big in size

### ISSUE THREAD

**Issue by akuzubasli** [jpmml/jpmml-h2o#12]
Hi @vruusmann,
I've converted an h2o DRF model (9 MB) but the output PMML is 200 MB, occupying almost 1 GB on RAM.
There seems to be no `compact` option to reduce size.

Do you have any idea what can be done?
Thanks.

**Comment by vruusmann** [comment]
> I've converted an h2o DRF model (9 MB) but the output PMML is 200 MB

MOJO is a compressed data format, PMML is a plain text data format. To make a relevant size comparison, you should compare 1) MOJO with compressed PMML, or 2) uncompressed MOJO with PMML.

PMML easily deflates 95% when compressed using the ZIP algorithm. So, you'd be looking at 9 MB MOJO vs 10-12 MB PMML here.

> .. occupying almost 1 GB on RAM.

What kind of PMML library do you use?

The JPMML-Model/JPMML-Evaluator stack uses a memory representation (eg. heavily interned elements, attributes), which is smaller than the on-disk representation.

A 200 MB PMML document should comfortably fit into 50-100 MB of RAM.

> There seems to be no compact option to reduce size.

Compaction won't help you if your PMML engine uses inefficient memory representation.

H2O.ai appears to be using binary splits identical to XGBoost/LightGBM/Scikit-Learn, so you may wish to develop a compacting visitor based on them.

**Comment by vruusmann** [comment]
Closing as "nothing to do for me here".

I don't have any customers depending on JPMML-H2O, so I'm more inclined to terminate this project, rather than waste more time on it.
