### ISSUE TITLE
Could this be used for models built with older version of H2O?

### ISSUE THREAD

**Issue by flippercy** [jpmml/jpmml-h2o#15]
Hi @vruusmann:

Could this be used for models built with older version of H2O, please? Will the MOJO file be different?

Thank you.

**Comment by vruusmann** [comment]
> Could this be used for models built with older version of H2O?

First, define "old".

The latest JPMML-H2O release version should work fine with all H2O.ai versions in 3.34 -- 3.42 range. When exceeding the "lower bound" of the version range, then the "supported state" will vary from one MOJO type to another. For example, random forests may work, and GLM may not, and so on.

> Will the MOJO file be different?

The MOJO content is mostly unchanged. But the MOJO public API field names, method signatures etc. may change, which will lead to all sort of JVM-level class incompatibility errors.

**Comment by vruusmann** [comment]
The JPMML-H2O project has been around for five years now (ie. since July 2018).

If you know that your MOJO was created in May 2020 (for example), then go to JPMML-H2O release archives, and choose the version that was released around the same time:
https://github.com/jpmml/jpmml-h2o/releases

Should be the highest success rate approach.

**Comment by flippercy** [comment]
My model (h2o.xgboost) was built in 2020 using h2o 3.30.0.7; any suggestions?

Thank you.

**Comment by vruusmann** [comment]
> My model was built in 2020 using h2o 3.30.0.7

Any early JPMML-H2O 1.1 version should be fine (1.1.0 -- 1.1.3).

> My model (h2o.xgboost)

However, XGBoost is a special case, because it is "external" to H2O.ai.

With XGBoost models, I'd first give the latest JPMML-H2O version a try - that would be version 1.2.8 (as of today).

**Comment by vruusmann** [comment]
> I've found the POJO file of the old model

Have not dealt with the POJO data format under this project.

Yesterday, I published some notes about the current state of Scikit-Learn H2O.ai pipelines:
https://openscoring.io/blog/2023/07/17/converting_sklearn_h2o_pipeline_pmml/
