### ISSUE TITLE
Throws and error when converting a poisson GBM to PMML

### ISSUE THREAD

**Issue by Paulo19920228** [jpmml/jpmml-h2o#3]
When trying to convert a poisson GBM built in H2O and exported as a MOJO to PMML format, I get the following error:
![jpmml-h2o](https://user-images.githubusercontent.com/47532484/52575113-8ca00900-2e15-11e9-8558-cecae0db5601.png)

I managed to solve this error by adding the following piece of code to the "\jpmml-h2o-master\src\main\java\org\jpmml\h2o\GbmMojoModelConverter.java" file:
``` java
if((DistributionFamily.poisson).equals(model._family)){
	ContinuousLabel continuousLabel = (ContinuousLabel)label;

	MiningModel miningModel = new MiningModel(MiningFunction.REGRESSION, ModelUtil.createMiningSchema(continuousLabel))
		.setSegmentation(MiningModelUtil.createSegmentation(MultipleModelMethod.SUM, treeModels))
		.setTargets(ModelUtil.createRescaleTargets(null, (double)model._init_f, continuousLabel));

	return miningModel;
} else
```
Once I added this piece of code (by copying the gaussian section and changing gaussian to poisson) the converter worked successfully, however, I'd like you to confirm whether this is okay and whether it can perhaps be added to the tool?

Thanks for your time.

Regards,
Paulo

**Comment by Paulo19920228** [comment]
It would also be great if you could add support for Tweedie GBM's.

Thanks,
Paulo

**Comment by vruusmann** [comment]
> I'd like you to confirm whether this is okay

That's exactly how easy/difficult it is to add support for a new objective function (OF).

However, `poisson` and `tweedie` OFs probably need an extra transformation step in the end - the prediction is in logiarithmic scale and needs to be translated back to the normal scale by applying the `exp` function.

I can recall this need when converting other GBT models such as XGBoost models. Will have to double-ceck with H2O source code to confirm.

**Comment by Paulo19920228** [comment]
Thanks for resolving this!
