### ISSUE TITLE
Missing number of values in the array

### ISSUE THREAD

**Issue by genicaalcaraz** [jpmml/jpmml-h2o#5]
Hi,
I tried to convert an H20 random forest model. If the variable uses a IsIn operator, i'm expecting to get a simple set predicate similar to the figure below. It should contain the number of values (n=?) in the array and quotes between the values.

![image](https://user-images.githubusercontent.com/49218659/58404446-b533d200-8097-11e9-9109-2a302ee6f028.png)

However, i'm getting these results (no n=? option and no quotes).
![image](https://user-images.githubusercontent.com/49218659/58404347-8289d980-8097-11e9-8e51-f677aca73555.png)

Please let me know your thoughts on how to fix this issue.
Let me know if you need additional info.
Thank you

**Comment by vruusmann** [comment]
The `Array@n` attribute is optional:
http://dmg.org/pmml/v4-3/GeneralStructure.html#Array

In the second example (field "embarked"), the Array element defines a three-element array - an empty string (`""`), and letters C and Q (`"C"` and `"Q"`).

The JPMML-H2O is generating perfectly valid PMML. Feel free to validate it against the XML Schema definition file.

**Comment by genicaalcaraz** [comment]
Thank you for the clarification @vruusmann.
