### ISSUE TITLE
release 1.0.10 is not compatible with h2o-3.28.x

### ISSUE THREAD

**Issue by zhuobao** [jpmml/jpmml-h2o#7]
release 1.0.10 is not compatible with h2o-3.28.x. When doing PMML conveting, generate error message like 
```bash
Exception in thread"main" ... MOJO version imcompatibility - the model MOJO version (1.10) is higher than the current h2o version (1.00) supports ...
    hex.genmodel.ModelMojoReader.checkMaxSupportedMojoVersion(ModelMojoReader.java:296)
    ...
    at org.jpmml.h2o.Main.main(Main.java:88)

```
rebuild with updated h2o dependency version does not solve the issue.

**Comment by vruusmann** [comment]
Next time, please paste the full stack trace of the exception into the comment box.

I rebuilt all JPMML-H2O integration tests with 3.28.0.3, and the reported exception only happens with XGBoost models. All "native" H2O models load/test without any problems.

**Comment by vruusmann** [comment]
> .. and the reported exception only happens with XGBoost models.

Because we've been using a custom `ModelMojoReader` class, which contains a hard-coded MOJO version `1.00`:
https://github.com/jpmml/jpmml-h2o/blob/1.0.10/src/main/java/org/jpmml/h2o/XGBoostMojoReader.java#L51

Replace this constant with `1.10` (or whatever else is required), and you'll be all set.
