### ISSUE TITLE
Handling of missing values

### ISSUE THREAD

**Issue by chandra-1998** [jpmml/jpmml-h2o#8]
I don't see support for missing values in mojo-pmml conversion.
While executing the pmml using jpmml-evaluator, the following error is thrown:
"Exception in thread "main" org.jpmml.evaluator.InvalidResultException : Field "X" cannot accept input value NaN".

This error doesn't appear for the jpmml-lightgbm package, since missing values are defined as 'NaN' in the pmml file.
Could the missing value handling be added to this jpmml-h2o package?

**Comment by vruusmann** [comment]
> I don't see support for missing values in mojo-pmml conversion.

Where did you look? Did you see this?
https://github.com/jpmml/jpmml-h2o/blob/1.1.4/src/main/java/org/jpmml/h2o/GlmMojoModelBaseConverter.java#L86-L111

> "Exception in thread "main" org.jpmml.evaluator.InvalidResultException : Field "X" cannot accept input value NaN".

According to PMML conventions, `NaN` is an **invalid** value, not a **missing** value.

If you want to signal to a model that a field value is missing, then you should be using Java's `null` reference value.

> Could the missing value handling be added to this jpmml-h2o package?

I believe you're simply confusing invalid and missing value handling.

To resolve the situation, please provide a reproducible code example (what you're aiming to do, what is expected to happen, what really happens).
